# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(unique=True)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=25)),
            ],
            options={
                'get_latest_by': 'occurence',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('weight', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('occurence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Occurence')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='occurence',
            unique_together=set([('timestamp', 'source')]),
        ),
        migrations.AddField(
            model_name='link',
            name='words',
            field=models.ManyToManyField(to='core.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('content_type', 'object_id', 'occurence')]),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('address', 'title')]),
        ),
    ]
